[default]
src = 'contracts'
out = 'out'
libs = ['node_modules']
test = 'foundry-test'
gas_reports = ["*"]
optimizer = true
optimizer_runs = 200

[profile.default]
solc = "0.8.20"

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 100 }


